FROM postgres:16-bookworm

# Copy in the extensions script
COPY extensions_postgres.sh /docker-entrypoint-initdb.d/

# Set permissions
RUN chmod 755 /docker-entrypoint-initdb.d/extensions_postgres.sh
